services:
  - type: web
    name: resume-analyzer
    env: python
    buildCommand: "pip install -r requirements.txt && python -m spacy download en_core_web_md"
    startCommand: "gunicorn --worker-class gthread --workers 1 --threads 100 run:app"
    envVars:
      - key: FLASK_ENV
        value: production
      - key: FLASK_DEBUG
        value: false
      - key: FORCE_HTTPS
        value: true
      - key: PYTHON_VERSION
        value: 3.11.0
